apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ejercicio11
  name: ejercicio11
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ejercicio11
  template:
    metadata:
      labels:
        app: ejercicio11
    spec:
      containers:
      - image: nicopaez/pingapp:2.1.0
        name: ejercicio11
        envFrom:
        - configMapRef:
            name: ejercicio11-c1
        volumeMounts:
          - mountPath: /mydata/
            name: c2-volume
          - mountPath: /mysecrets/
            name: s1-volume
      volumes:
      - name: c2-volume
        configMap:
          name: ejercicio11-c2
      - name: s1-volume
        secret:
          secretName: ejercicio11-s1
