apiVersion: v1
kind: Secret
metadata:
  name: jobvacancysecret
  labels:
    app: jobvacancy
type: Opaque
data:
  # echo -n postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...] | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkMUBkYjovcG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: jobvacancydbsecret
  labels:
    app: jobvacancy
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQx