version: '2'
services:
  passwordapi1:
    image: nicopaez/password-api:latest
  passwordapi2:
    image: nicopaez/password-api:latest
  nginx:
    image: nginx:1.23.0
    ports:
      - "8080:80"
    links:
      - passwordapi1
      - passwordapi2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

